export const CONTEXT_EXAMPLE_CHANGE_USERNAME = 'CONTEXT_EXAMPLE_CHANGE_USERNAME';
export const CONTEXT_EXAMPLE_ADD_LIKE = 'CONTEXT_EXAMPLE_ADD_LIKE';
export const CONTEXT_EXAMPLE_REMOVE_LIKE = 'CONTEXT_EXAMPLE_REMOVE_LIKE';